parameters:
  app.url: '%env(APP_URL)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      string $appUrl: '%app.url%'

  App\:
    resource: '../src/'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\ValueResolver\RequestFileResolver:
    tags:
      - { name: "controller.argument_value_resolver", priority: 90 }
  App\ValueResolver\RequestFormDataResolver:
    tags:
      - { name: "controller.argument_value_resolver", priority: 100 }
  Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    arguments:
      $classMetadataFactory: '@serializer.mapping.class_metadata_factory'
      $nameConverter: null
      $propertyTypeExtractor: '@property_info'
      $propertyAccessor: '@property_accessor'
  Aws\S3\S3Client:
    class: Aws\S3\S3Client
    arguments:
      - version: 'latest'
        region: '%env(AWS_REGION)%'
        credentials:
          key: '%env(AWS_ACCESS_KEY_ID)%'
          secret: '%env(AWS_SECRET_ACCESS_KEY)%'
  App\Service\Image\S3ImageService:
    lazy: true
    arguments:
      $s3: ''
      $bucket: '%env(AWS_BUCKET_NAME)%'
      $path: 'images/uploads/'

  App\Service\Image\DirectoryImageService:
    arguments:
      $path: '%kernel.project_dir%/public/uploads'
  App\Factory\ImageServiceFactory:
    arguments:
      $key: '%env(default::AWS_ACCESS_KEY_ID)%'
  App\Service\Image\ImageServiceInterface:
    factory: [ '@App\Factory\ImageServiceFactory', 'create' ]

